//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinyBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int order_id { get; set; }
        public int payment_id { get; set; }
        public int delivery_id { get; set; }
        public int account_id { get; set; }
        public Nullable<int> order_address_id { get; set; }
        public System.DateTime order_date { get; set; }
        public double total { get; set; }
        public string status { get; set; }
        public string order_note { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public System.DateTime update_at { get; set; }
        public string update_by { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual OrderAddress OrderAddress { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
