//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinyBookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments = new HashSet<Comment>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product_Img = new HashSet<Product_Img>();
        }
    
        public int product_id { get; set; }
        public int genre_id { get; set; }
        public int discount_id { get; set; }
        public int publisher_id { get; set; }
        public string product_name { get; set; }
        public double price { get; set; }
        public long view { get; set; }
        public long buyturn { get; set; }
        private string _quantity;
        [StringLength(10)]
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        public string quantity
        {
            get { return ((this._quantity != "" && this._quantity != null) ? this._quantity.Trim() : this._quantity); }
            set { this._quantity = (value == null) ? "" : value.Trim(); }
        }
        public string status { get; set; }
        public Nullable<int> type { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string product_information { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public System.DateTime update_at { get; set; }
        public string update_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Img> Product_Img { get; set; }
        public virtual Publisher Publisher { get; set; }
        //[ValidateFile(ErrorMessage = "Please select a PNG image smaller than 1MB")]
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }


        //[ValidateFile(ErrorMessage = "Please select a PNG image smaller than 1MB")]
        [NotMapped]
        public HttpPostedFileBase[] ImageUploadMulti { get; set; }
    }
}
