//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinyBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelyComment
    {
        public int rep_comment_id { get; set; }
        public int account_id { get; set; }
        public int comment_id { get; set; }
        public string content { get; set; }
        public string status { get; set; }
        public System.DateTime create_at { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Comment Comment { get; set; }
    }
}
